apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: invensys-ingress
  namespace: default
  labels:
    app: invensys
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
spec:
  rules:
    - host: invensys.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: invensys-nginx
                port:
                  number: 80
