apiVersion: v1
kind: Secret
metadata:
  name: invensys-secret
  namespace: default
  labels:
    app: invensys
type: Opaque
stringData:
  APP_KEY: "base64:9gYiW0S/QjE6D4ZF34898UoFwvUxjLgEXk6gijuct6I="
  DB_USERNAME: "invensys"
  DB_PASSWORD: "invensys_pass123"
  DB_ROOT_PASSWORD: "rootsecret123"

---
# Secret khusus MySQL environment
apiVersion: v1
kind: Secret
metadata:
  name: invensys-mysql-secret
  namespace: default
  labels:
    app: invensys
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootsecret123"
  MYSQL_DATABASE: "inventory_system"
  MYSQL_USER: "invensys"
  MYSQL_PASSWORD: "invensys_pass123"
